---

- name: restart elasticsearch
  systemd:
    state: restarted
    daemon_reload: yes
    name: elasticsearch.service
  listen: restart_elasticsearch

    
- name: Wait for elasticsearch to be OK
  command: "{{ base_directory }}/elasticsearch/elasticsearch-healthcheck.sh"
  register: result
  until: result.rc == 0
  retries: 10
  delay: 20
  listen: restart_elasticsearch

  
...
